# Generated by Django 5.2.5 on 2025-09-03 18:58

import django.db.models.deletion
import judge.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="نام")),
                (
                    "dockerfile_path",
                    models.FileField(
                        upload_to=judge.models.dockerfile_upload_path,
                        verbose_name="مسیر فایل داکر",
                    ),
                ),
                (
                    "run_command",
                    models.CharField(max_length=256, verbose_name="دستور اجرا"),
                ),
                (
                    "compile_command",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="دستور کامپایل",
                    ),
                ),
                (
                    "need_compile",
                    models.BooleanField(
                        default=False, verbose_name="کامپایل نیاز دارد؟"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="پسوند"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "زبان برنامه نویسی",
                "verbose_name_plural": "زبان\u200cهای برنامه نویسی",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Normal", "Normal"),
                            ("Hard", "Hard"),
                        ],
                        max_length=16,
                        verbose_name="درجه سختی",
                    ),
                ),
                (
                    "input_format",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="فرمت ورودی",
                    ),
                ),
                (
                    "output_format",
                    models.TextField(max_length=128, verbose_name="فرمت خروجی"),
                ),
                (
                    "memory_limit_kb",
                    models.IntegerField(default=25600, verbose_name="محدودیت مموری"),
                ),
                (
                    "time_limit_ms",
                    models.IntegerField(default=1000, verbose_name="محدودیت زمانی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        to="judge.programminglanguage",
                        verbose_name="زبان\u200cهای برنامه نویسی",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوال\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_code", models.TextField(verbose_name="کد")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Queued", "Queued"),
                            ("Running", "Running"),
                            ("Done", "Done"),
                            ("Error", "Error"),
                        ],
                        max_length=32,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("CE", "Compile Error"),
                        ],
                        max_length=32,
                        verbose_name="نتیجه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.programminglanguage",
                        verbose_name="زبان برنامه\u200cنویسی",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.problem",
                        verbose_name="سوال",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارسال",
                "verbose_name_plural": "ارسال\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField(verbose_name="ورودی")),
                ("expected_output", models.TextField(verbose_name="خروجی قابل انتظار")),
                (
                    "is_sample",
                    models.BooleanField(default=False, verbose_name="مثال است؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.problem",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "تست کیس",
                "verbose_name_plural": "تست کیس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("CE", "Compile Error"),
                        ],
                        max_length=32,
                        verbose_name="نتیجه",
                    ),
                ),
                ("time_ms", models.IntegerField(default=0, verbose_name="زمان")),
                ("memory_kb", models.IntegerField(default=0, verbose_name="مموری")),
                (
                    "stdout",
                    models.TextField(
                        blank=True, default="", verbose_name="خروجی استاندارد"
                    ),
                ),
                (
                    "stderr",
                    models.TextField(
                        blank=True, default="", verbose_name="استاندارد ارور"
                    ),
                ),
                ("exit_code", models.IntegerField(default=0, verbose_name="کد حطا")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.submission",
                        verbose_name="ارسال",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.testcase",
                        verbose_name="تست کیس",
                    ),
                ),
            ],
            options={
                "verbose_name": "نتیحه تست کیس",
                "verbose_name_plural": "نتایج تست کیس\u200cها",
            },
        ),
    ]
