# Generated by Django 5.1.6 on 2025-08-24 15:58

import django.db.models.deletion
import judge.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "dockerfile_path",
                    models.FileField(upload_to=judge.models.dockerfile_upload_path),
                ),
                ("run_command", models.CharField(max_length=256)),
                (
                    "compile_command",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("need_compile", models.BooleanField(default=False)),
                ("extension", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Normal", "Normal"),
                            ("Hard", "Hard"),
                        ],
                        max_length=16,
                    ),
                ),
                ("input_format", models.TextField(max_length=128)),
                ("output_format", models.TextField(max_length=128)),
                ("memory_limit_kb", models.IntegerField(default=256000)),
                ("time_limit_ms", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("languages", models.ManyToManyField(to="judge.programminglanguage")),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Queued", "Queued"),
                            ("Running", "Running"),
                            ("Done", "Done"),
                            ("Error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("Accepted", "AC"),
                            ("Wrong Answer", "WA"),
                            ("Time Limit Exceeded", "TLE"),
                            ("Memory Limit Exceeded", "MLE"),
                            ("Runtime Error", "RE"),
                            ("Compile Error", "CE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.programminglanguage",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_sample", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("Accepted", "AC"),
                            ("Wrong Answer", "WA"),
                            ("Time Limit Exceeded", "TLE"),
                            ("Memory Limit Exceeded", "MLE"),
                            ("Runtime Error", "RE"),
                            ("Compile Error", "CE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("time_ms", models.IntegerField(default=0)),
                ("memory_kb", models.IntegerField(default=0)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                ("exit_code", models.IntegerField(default=0)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.submission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.testcase"
                    ),
                ),
            ],
        ),
    ]
