# Generated by Django 5.2.5 on 2025-09-03 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"verbose_name": "سوال", "verbose_name_plural": "سوالات"},
        ),
        migrations.AlterField(
            model_name="programminglanguage",
            name="need_compile",
            field=models.BooleanField(
                default=False, verbose_name="به کامپایل نیاز دارد؟"
            ),
        ),
        migrations.AlterField(
            model_name="testcaseresult",
            name="exit_code",
            field=models.IntegerField(default=0, verbose_name="کد خطا"),
        ),
        migrations.CreateModel(
            name="ScoreAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "problem"), name="unique_user_problem"
                    )
                ],
            },
        ),
    ]
