# Generated by Django 5.1.6 on 2025-08-26 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="problem",
            name="input_format",
            field=models.TextField(blank=True, default="", max_length=128),
        ),
    ]
