# Generated by Django 5.2.5 on 2025-08-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0002_testcaseresult_created_at_alter_problem_input_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="programminglanguage",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("Queued", "Queued"),
                    ("Running", "Running"),
                    ("Done", "Done"),
                    ("Error", "Error"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("AC", "Accepted"),
                    ("WA", "Wrong Answer"),
                    ("TLE", "Time Limit Exceeded"),
                    ("MLE", "Memory Limit Exceeded"),
                    ("RE", "Runtime Error"),
                    ("CE", "Compile Error"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="testcaseresult",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("AC", "Accepted"),
                    ("WA", "Wrong Answer"),
                    ("TLE", "Time Limit Exceeded"),
                    ("MLE", "Memory Limit Exceeded"),
                    ("RE", "Runtime Error"),
                    ("CE", "Compile Error"),
                ],
                max_length=32,
            ),
        ),
    ]
